
@api = http://127.0.0.1:9292

@username = {{$dotenv BASIC_AUTH_USERNAME}}
@password = {{$dotenv BASIC_AUTH_PASSWORD}}

###

GET {{api}}/health

###

POST {{api}}/aggregate
Authorization: Basic {{username}} {{password}}

###

GET {{api}}/aggregated_results.json

###

GET {{api}}/

###

OPTIONS {{api}}/

